version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:7.12.1
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
      # Force publishing on the 'elk' overlay.
      network.publish_host: _eth0_
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - elk
      - app
    deploy:
      replicas: 1
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline_v2
        target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
      - app
    deploy:
      replicas: 1
  kibana:
    image: kibana:7.11.1
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
    networks:
      - elk
    deploy:
      replicas: 1
  logspout:
    image: bekt/logspout-logstash
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ROUTE_URIS: logstash://logstash:5000
      LOGSTASH_TAGS: "docker-elk"
    networks:
      - elk
      - app
    depends_on:
      - logstash
    deploy:
      replicas: 1
configs:
  elastic_config:
    file: ./elasticsearch.yml
  logstash_config:
    file: ./logstash.yml
  logstash_pipeline_v2:
    file: ./logstash-pipeline.conf
  kibana_config:
    file: ./kibana.yml
volumes:
  elastic:
networks:
  elk:
    driver: overlay
  app:
    external: true
