version: '3.8'

services:
  mysql:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password --wait_timeout=864000
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
  redis:
    image: redis:6.0.9-alpine3.12
    ports:
      - 6379:6379
    volumes:
      - ./../data/redis:/data
