version: '3.8'

services:
  app:
    image: $APP_IMAGE
    environment:
      PORT: 3333
      HOST: 0.0.0.0
      NODE_ENV: development
      APP_KEY: 3_7yprD0-_s1L_Wc6w81cbhcxhodx9q_
      SESSION_DRIVER: cookie
      CACHE_VIEWS: 0
      DB_CONNECTION: mysql
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DB_NAME: app
      SESSION_DRIVER: redis
      REDIS_CONNECTION: local
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TREE_VISUALIZE_URL: http://python-app:8000/get-tree
    command: sh -c "node ace db:wait && node ace migration:run && node ace db:seed && node japaFile.js test/**/*.spec.js"
    networks:
      - default
  mysql:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password --wait_timeout=864000
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_HOST: '%'
    networks:
      - default
  redis:
    image: redis:6.0.9-alpine3.12
    networks:
      - default

